// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Event struct {
	ID           int64          `json:"id"`
	RunID        sql.NullString `json:"run_id"`
	ExperimentID sql.NullInt64  `json:"experiment_id"`
	Ts           sql.NullTime   `json:"ts"`
	Level        sql.NullString `json:"level"`
	Message      sql.NullString `json:"message"`
}

type Experiment struct {
	ID         int64          `json:"id"`
	RunID      sql.NullString `json:"run_id"`
	Name       string         `json:"name"`
	Kind       string         `json:"kind"`
	Type       string         `json:"type"`
	Status     string         `json:"status"`
	StartedAt  sql.NullTime   `json:"started_at"`
	FinishedAt sql.NullTime   `json:"finished_at"`
}

type Run struct {
	ID         string       `json:"id"`
	Repo       string       `json:"repo"`
	PrNumber   int32        `json:"pr_number"`
	CommitSha  string       `json:"commit_sha"`
	Engine     string       `json:"engine"`
	Status     string       `json:"status"`
	CreatedAt  sql.NullTime `json:"created_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}
