// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (run_id, experiment_id, level, message)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, experiment_id, ts, level, message
`

type CreateEventParams struct {
	RunID        sql.NullString `json:"run_id"`
	ExperimentID sql.NullInt64  `json:"experiment_id"`
	Level        sql.NullString `json:"level"`
	Message      sql.NullString `json:"message"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.RunID,
		arg.ExperimentID,
		arg.Level,
		arg.Message,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ExperimentID,
		&i.Ts,
		&i.Level,
		&i.Message,
	)
	return i, err
}

const createExperiment = `-- name: CreateExperiment :one
INSERT INTO experiments (run_id, name, kind, type, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, name, kind, type, status, started_at, finished_at
`

type CreateExperimentParams struct {
	RunID  sql.NullString `json:"run_id"`
	Name   string         `json:"name"`
	Kind   string         `json:"kind"`
	Type   string         `json:"type"`
	Status string         `json:"status"`
}

func (q *Queries) CreateExperiment(ctx context.Context, arg CreateExperimentParams) (Experiment, error) {
	row := q.db.QueryRowContext(ctx, createExperiment,
		arg.RunID,
		arg.Name,
		arg.Kind,
		arg.Type,
		arg.Status,
	)
	var i Experiment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, repo, pr_number, commit_sha, engine, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo, pr_number, commit_sha, engine, status, created_at, finished_at
`

type CreateRunParams struct {
	ID        string `json:"id"`
	Repo      string `json:"repo"`
	PrNumber  int32  `json:"pr_number"`
	CommitSha string `json:"commit_sha"`
	Engine    string `json:"engine"`
	Status    string `json:"status"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.Repo,
		arg.PrNumber,
		arg.CommitSha,
		arg.Engine,
		arg.Status,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.PrNumber,
		&i.CommitSha,
		&i.Engine,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getEventsForRun = `-- name: GetEventsForRun :many
SELECT id, run_id, experiment_id, ts, level, message FROM events WHERE run_id = $1 ORDER BY ts ASC
`

func (q *Queries) GetEventsForRun(ctx context.Context, runID sql.NullString) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ExperimentID,
			&i.Ts,
			&i.Level,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExperimentsForRun = `-- name: GetExperimentsForRun :many
SELECT id, run_id, name, kind, type, status, started_at, finished_at FROM experiments WHERE run_id = $1
`

func (q *Queries) GetExperimentsForRun(ctx context.Context, runID sql.NullString) ([]Experiment, error) {
	rows, err := q.db.QueryContext(ctx, getExperimentsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experiment
	for rows.Next() {
		var i Experiment
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Kind,
			&i.Type,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingRuns = `-- name: GetPendingRuns :many
SELECT id, repo, pr_number, commit_sha, engine, status, created_at, finished_at FROM runs WHERE status = 'pending' ORDER BY created_at ASC LIMIT 10
`

func (q *Queries) GetPendingRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.PrNumber,
			&i.CommitSha,
			&i.Engine,
			&i.Status,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, repo, pr_number, commit_sha, engine, status, created_at, finished_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.PrNumber,
		&i.CommitSha,
		&i.Engine,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAllRuns = `-- name: ListAllRuns :many
SELECT id, repo, pr_number, commit_sha, engine, status, created_at, finished_at FROM runs ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListAllRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listAllRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.PrNumber,
			&i.CommitSha,
			&i.Engine,
			&i.Status,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExperimentStatus = `-- name: UpdateExperimentStatus :one
UPDATE experiments
SET status = $2, started_at = COALESCE(started_at, $3), finished_at = $4
WHERE id = $1
RETURNING id, run_id, name, kind, type, status, started_at, finished_at
`

type UpdateExperimentStatusParams struct {
	ID         int64        `json:"id"`
	Status     string       `json:"status"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

func (q *Queries) UpdateExperimentStatus(ctx context.Context, arg UpdateExperimentStatusParams) (Experiment, error) {
	row := q.db.QueryRowContext(ctx, updateExperimentStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Experiment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $2, finished_at = $3
WHERE id = $1
RETURNING id, repo, pr_number, commit_sha, engine, status, created_at, finished_at
`

type UpdateRunStatusParams struct {
	ID         string       `json:"id"`
	Status     string       `json:"status"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunStatus, arg.ID, arg.Status, arg.FinishedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.PrNumber,
		&i.CommitSha,
		&i.Engine,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
