// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateExperiment(ctx context.Context, arg CreateExperimentParams) (Experiment, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	GetEventsForRun(ctx context.Context, runID sql.NullString) ([]Event, error)
	GetExperimentsForRun(ctx context.Context, runID sql.NullString) ([]Experiment, error)
	GetPendingRuns(ctx context.Context) ([]Run, error)
	GetRun(ctx context.Context, id string) (Run, error)
	ListAllRuns(ctx context.Context) ([]Run, error)
	UpdateExperimentStatus(ctx context.Context, arg UpdateExperimentStatusParams) (Experiment, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error)
}

var _ Querier = (*Queries)(nil)
